dbt_repo:
  outputs:
    dev:
      account: UXCMRWI-UI26533
      database: DEV
      password: Oracle@7259045856
      role: ACCOUNTADMIN
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: SATYADBTDEMO
      warehouse: COMPUTE_WH
  target: dev
